package corejava;

public class Try_Catch {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int d = 0;
		int n = 20;
		try {
		int fraction = n/d;
		System.out.println("End of Main");
		}
		catch(Exception e)//handles any kind of exception
			{
			
			System.out.println("you cannot divide by zero");
		}
	}

}
